- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes


- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Copy index test page
  template:
    src: "backend/artifact.tar.gz"
    dest: "~/backend/artifact.tar.gz"

- name: Extract foo.tgz into /var/lib/foo
  ansible.builtin.unarchive:
    src: artifact.tar.gz
    dest: ~/

- name: "start server"
  shell: |
    cd ~/backend
    npm install
    pm2 stop default
    pm2 start npm -- start