- name: "Copy backend tar.gz"
  become: yes
  ansible.builtin.unarchive:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu

- name: "installing dependencies"
  become: yes
  npm:
    path: /home/ubuntu

- name: "start server"
  shell: |
    cd /home/ubuntu
    pm2 stop default
    pm2 start npm -- start
