- name: Copy index test page
  template:
    src: "/root/project/artifact.tar.gz"
    dest: "~/artifact.tar.gz"

- name: Extract foo.tgz into /var/lib/foo
  ansible.builtin.unarchive:
    src: ~/artifact.tar.gz
    dest: ~/backend

- name: "start server"
  shell: |
    cd ~/backend
    npm install
    pm2 stop default
    pm2 start npm -- start